name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
# downloads the app from github to the virtual machine workflows uses 
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
# installs the node js environment 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
# installs all dependencies 
      - name: Install deps
        run: npm install
# auth test cases 
      - name: Run tests
        run: npm test

      # Build Docker image 
      - name: Build Docker image
        run: |
          docker build \
            --build-arg COMMIT_SHA=${{ github.sha }} \
            -t pipeline-demo:${{ github.sha }} .
